### Get a sample post
GET https://jsonplaceholder.typicode.com/posts/1
 
### Create a new post
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json
 
{
    "title": "Hello VS Code",
    "body": "Testing APIs is easy!",
    "userId": 1
}
 
### Get all posts
GET https://jsonplaceholder.typicode.com/posts
 